[package]
name = "modern-sysu-report"
version = "0.4.0"
entrypoint = "lib.typ"
authors = ["wisestruct"]
license = "MIT"
description = "中山大学博士学位论文开题报告Typst模板。"
repository = "https://github.com/wisestruct/modern-sysu-report"
keywords = ["Shanghai Jiao Tong University", "thesis"]
categories = ["thesis"]
exclude = ["imgs"]

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"
